# Generated by Django 2.2 on 2019-04-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedpages',
            name='links',
            field=models.URLField(max_length=255),
        ),
    ]
