# Generated by Django 2.2 on 2019-04-19 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedPages',
        ),
    ]
