# Generated by Django 2.2 on 2019-04-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190419_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedpages',
            name='links',
            field=models.URLField(max_length=512),
        ),
    ]
