# Generated by Django 2.1.7 on 2019-03-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190323_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='offered',
            field=models.CharField(max_length=50),
        ),
    ]
