# Generated by Django 2.1.7 on 2019-03-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20190323_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='credit_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='cross_listed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='offered',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='prerequisites',
            field=models.TextField(blank=True, null=True),
        ),
    ]
