# Generated by Django 2.1.7 on 2019-03-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20190323_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseInfo',
        ),
    ]
