# Generated by Django 2.1.7 on 2019-03-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20190323_1808'),
        ('info', '0006_courseinfo'),
    ]

    operations = [
    ]
