# Generated by Django 2.1.7 on 2019-03-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20190323_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfAndCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(default='', max_length=20)),
                ('prof_name', models.TextField()),
            ],
        ),
    ]
