# Generated by Django 2.1.7 on 2019-03-23 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_profandcourses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfAndCourses',
        ),
    ]
