# Generated by Django 2.1.7 on 2019-03-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20190323_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('dept', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web_page', models.URLField(blank=True, max_length=255, null=True)),
                ('focus', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
