# Generated by Django 2.1.7 on 2019-03-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_delete_profandcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfAndCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(default='', max_length=20)),
                ('dept', models.TextField()),
                ('code_digit', models.TextField()),
                ('prof', models.TextField()),
                ('section', models.TextField()),
                ('credit', models.TextField()),
                ('days', models.TextField()),
                ('time', models.TextField()),
                ('date', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
