# Generated by Django 2.1.7 on 2019-03-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20190323_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profinfo',
            name='focus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
