# Generated by Django 2.1.7 on 2019-03-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20190323_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profinfo',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
