# Generated by Django 2.1.7 on 2019-03-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20190323_2227'),
        ('info', '0009_profandcourses'),
    ]

    operations = [
    ]
