# Generated by Django 2.1.7 on 2019-03-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_merge_20190324_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='profandcourses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profandcourses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='profandcourses',
            name='code_digit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profandcourses',
            name='credit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profandcourses',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profandcourses',
            name='days',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profandcourses',
            name='dept',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profandcourses',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profandcourses',
            name='prof',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profandcourses',
            name='section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profandcourses',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
