# Generated by Django 2.1.7 on 2019-03-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_auto_20190324_0252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profandcourses',
            options={'get_latest_by': ['updated_at']},
        ),
    ]
