# Generated by Django 2.1.7 on 2019-03-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20190324_1515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseInfo',
        ),
    ]
