# Generated by Django 2.2 on 2019-04-13 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_courseinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.CourseInfo')),
            ],
        ),
    ]
