# Generated by Django 2.2 on 2019-04-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_relatedpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedpages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='relatedpages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
