# Generated by Django 2.2 on 2019-04-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_auto_20190413_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedpages',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
